[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Matt Smith <trebinor@users.noreply.github.com>"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.8"
regex = "1"
num = "0.2"
rand = "0.7"
